# Generated by Django 5.0.3 on 2024-04-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot_central',
            fields=[
                ('id_entrepot_central', models.AutoField(primary_key=True, serialize=False)),
                ('nom_entrepot_central', models.CharField(max_length=100)),
                ('adresse_entrepot_central', models.CharField(max_length=100)),
                ('telephone_entrepot_central', models.CharField(max_length=100)),
                ('email_entrepot_central', models.CharField(max_length=100)),
                ('responsable_entrepot_central', models.CharField(max_length=100)),
                ('entrp_stock', models.IntegerField()),
                ('entrp_prevision', models.FileField(upload_to='prevision/')),
            ],
        ),
    ]
