# Generated by Django 5.0.3 on 2024-04-25 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepot_central',
            name='responsable_entrepot_central',
        ),
        migrations.AlterField(
            model_name='entrepot_central',
            name='entrp_prevision',
            field=models.FileField(upload_to='prevision_total/'),
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id_depot', models.AutoField(primary_key=True, serialize=False)),
                ('nom_depot', models.CharField(max_length=100)),
                ('zone_depot', models.CharField(max_length=100)),
                ('telephone_depot', models.CharField(max_length=100)),
                ('stock_depot', models.IntegerField()),
                ('prevision_depot', models.FileField(upload_to='prevision/')),
                ('id_entrepot_central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRP.entrepot_central')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id_historique', models.AutoField(primary_key=True, serialize=False)),
                ('hist_data', models.FileField(upload_to='historique/')),
                ('id_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRP.depot')),
            ],
        ),
    ]
