# Generated by Django 5.0.3 on 2024-06-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRP', '0003_remove_depot_telephone_depot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='id_entrepot_central',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DRP.entrepot_central'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='id_depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DRP.depot'),
        ),
    ]
