# Generated by Django 5.0.3 on 2024-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRP', '0004_alter_depot_id_entrepot_central_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='hist_data',
            field=models.FileField(blank=True, null=True, upload_to='historique/'),
        ),
        migrations.DeleteModel(
            name='Historique',
        ),
    ]
